
name = 'NL_air_2050_kerosene'
frequency = 'W-MON'
modified_instances = [2, 4, 12, 26, 47, 48, 49, 50]
modification_factors = [0.89, 0.89, 0.26, 0.26, 0.26, 0.42, 0.77, 0.89]
[run_start]
year = 2018
month = 1
day = 1
hour = 0
[run_end]
year = 2019
month = 1
day = 1
hour = 0
