
name = 'NL_dometsic-aviation_2040_Aviation gasoline'
growth = 1.25
frequency = 'W-MON'
modified_instances = [2, 4, 12, 26, 47, 48, 49, 50]
modification_factors = [0.89, 0.89, 0.26, 0.26, 0.26, 0.42, 0.77, 0.89]
recurring_modifications_starts = [2]
recurring_modifications = [0.5]
recurrences_steps = [2]
amounts_of_recurrences = [0] # If set to zero, repeats for whole run
[run_start]
year = 2018
month = 1
day = 1
hour = 0
[run_end]
year = 2019
month = 1
day = 1
hour = 0
