site_name: ChaProEV
nav:
  - Home: index.md
  - User guide:
    - How to use: using.md
    - Creating scenarios: scenario.md
    - Variants: variants.md
    - Inputs: input.md
    - General parameters: general_parameters.md
  - Approach:
    - Outputs: outputs.md
  - Modules: 
    - Weather: weather.md
    - Run time: run_time.md
    - Define: define.md
    - Mobility: mobility.md
    - Charging: charging.md
    - Consumption: consumption.md
    - Variants: make_variants.md
    - Running model: running_model.md
    - Multiprocessing: multiprocessing.md
    - Writing: writing.md
    - Scenarios: scenarios_module.md
    - Profiles: profiles.md

theme: 
  name: readthedocs
  sticky_navigation: False

